In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('HousingData.csv')

In [3]:
cols = df.columns

In [4]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93   0.0  0.573  6.030   NaN  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90    NaN  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99    NaN  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [5]:
arr_column = []

In [6]:
missing_rows = []

In [7]:
row_miss = []

In [8]:
import numpy as np

In [9]:
from sklearn.impute import KNNImputer

In [10]:
imputer = KNNImputer(n_neighbors=4, weights="uniform")

In [11]:
df = imputer.fit_transform(df)

In [12]:
df

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 3.9690e+02, 4.9800e+00,
        2.4000e+01],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 3.9690e+02, 9.1400e+00,
        2.1600e+01],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 3.9283e+02, 4.0300e+00,
        3.4700e+01],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 5.6400e+00,
        2.3900e+01],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 3.9345e+02, 6.4800e+00,
        2.2000e+01],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 3.9690e+02, 7.8800e+00,
        1.1900e+01]])

In [13]:
df_ = pd.DataFrame(data = df,columns=cols)

In [14]:
df = df_

In [15]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM     AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.200  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.900  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.100  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.800  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.200  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...     ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.100  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.700  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.000  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.300  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  81.525  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90  4.980  24.0  
1       17.8  396.90  9.140  21.6  
2       17.8  392.83  4.030  34.7  
3       18.7  394.63  2.940  33.4  
4       18.7  396.90  6.810  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99  9.675  22.4  
502     21.0  396.90  9.080  20.6  
503     21.0  396.90  5.640  23.9  
504     21.0  393.45  6.480  22.0  
505     21.0  396.90  7.880  11.9  

[506 rows x 14 columns]

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
scaler = StandardScaler()

In [18]:
y_val = df['MEDV']

In [19]:
df = df.drop(columns = ['MEDV'], axis=1)

In [20]:
scaler.fit(df)

StandardScaler()

In [21]:
df1 = scaler.transform(df)

In [22]:
df1

array([[-0.42456802,  0.28947848, -1.29115682, ..., -1.45900038,
         0.44105193, -1.08543884],
       [-0.42216572, -0.4882421 , -0.59515454, ..., -0.30309415,
         0.44105193, -0.49861026],
       [-0.42216801, -0.4882421 , -0.59515454, ..., -0.30309415,
         0.39642699, -1.21945017],
       ...,
       [-0.41833739, -0.4882421 ,  0.11546964, ...,  1.17646583,
         0.44105193, -0.99233623],
       [-0.41274882, -0.4882421 ,  0.11546964, ...,  1.17646583,
         0.4032249 , -0.87384199],
       [-0.41986529, -0.4882421 ,  0.11546964, ...,  1.17646583,
         0.44105193, -0.67635161]])

In [23]:
df = pd.DataFrame(data = df1,columns=cols[:-1])

In [24]:
df

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0   -0.424568  0.289478 -1.291157 -0.277097 -0.144217  0.413672 -0.126989   
1   -0.422166 -0.488242 -0.595155 -0.277097 -0.740262  0.194274  0.367485   
2   -0.422168 -0.488242 -0.595155 -0.277097 -0.740262  1.282714 -0.274970   
3   -0.421587 -0.488242 -1.310165 -0.277097 -0.835284  1.016303 -0.827192   
4   -0.417389 -0.488242 -1.310165 -0.277097 -0.835284  1.228577 -0.524011   
..        ...       ...       ...       ...       ...       ...       ...   
501 -0.418123 -0.488242  0.115470 -0.277097  0.158124  0.439316  0.013774   
502 -0.420110 -0.488242  0.115470 -0.277097  0.158124 -0.234548  0.288080   
503 -0.418337 -0.488242  0.115470 -0.277097  0.158124  0.984960  0.804210   
504 -0.412749 -0.488242  0.115470 -0.277097  0.158124  0.725672  0.742852   
505 -0.419865 -0.488242  0.115470 -0.277097  0.158124 -0.362767  0.462229   

          DIS       RAD       TAX   PTRATIO         B     LSTAT  
0    0.140214 -0.982843 -0.666608 -1.459000  0.441052 -1.085439  
1    0.557160 -0.867883 -0.987329 -0.303094  0.441052 -0.498610  
2    0.557160 -0.867883 -0.987329 -0.303094  0.396427 -1.219450  
3    1.077737 -0.752922 -1.106115  0.113032  0.416163 -1.373211  
4    1.077737 -0.752922 -1.106115  0.113032  0.441052 -0.827291  
..        ...       ...       ...       ...       ...       ...  
501 -0.625796 -0.982843 -0.803212  1.176466  0.387217 -0.423141  
502 -0.716639 -0.982843 -0.803212  1.176466  0.441052 -0.507074  
503 -0.773684 -0.982843 -0.803212  1.176466  0.441052 -0.992336  
504 -0.668437 -0.982843 -0.803212  1.176466  0.403225 -0.873842  
505 -0.613246 -0.982843 -0.803212  1.176466  0.441052 -0.676352  

[506 rows x 13 columns]

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(df, y_val, random_state=0, train_size = .70)

In [27]:
X_train

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
141 -0.238894 -0.488242  1.571811 -0.277097  0.598679 -1.803097  1.129047   
272 -0.412175  0.375892 -0.611239 -0.277097 -0.783454  0.360960 -0.361593   
135 -0.361454 -0.488242  1.571811 -0.277097  0.598679  0.071754  1.064079   
298 -0.417891  2.536227 -1.301392 -0.277097 -1.336307  0.086000 -1.754782   
122 -0.414649 -0.488242  2.121594 -0.277097  0.227231 -0.461069  0.872787   
..        ...       ...       ...       ...       ...       ...       ...   
323 -0.392797 -0.488242 -0.549827 -0.277097 -0.532942 -0.821507  0.201457   
192 -0.414450  1.456059 -1.125929 -0.277097 -1.016689  1.272741 -1.531005   
117 -0.408012 -0.488242 -0.165271 -0.277097 -0.066472 -0.375589  0.501029   
47  -0.399052 -0.488242 -0.675575 -0.277097 -0.921667 -0.362767  0.605699   
172 -0.409367 -0.488242 -1.036736 -0.277097 -0.386091 -1.015261  0.713977   

          DIS       RAD       TAX   PTRATIO         B     LSTAT  
141 -1.119800 -0.637962  0.170831  1.268938  0.441052  3.066091  
272  0.058212 -0.752922 -1.100176  0.066796  0.419781 -0.697511  
135 -0.800685 -0.637962  0.170831  1.268938  0.416601  0.604515  
298  1.917048 -0.523001 -0.298373 -1.690182  0.126813 -1.086849  
122 -0.811998 -0.867883 -1.308051  0.297977  0.234812  0.741347  
..        ...       ...       ...       ...       ...       ...  
323  0.440219 -0.523001 -0.720062  0.529158  0.377788 -0.131842  
192  1.276251 -0.523001 -0.060801 -1.505237  0.370770 -1.383085  
117 -0.498017 -0.408041  0.141134 -0.303094  0.414847 -0.334975  
47   0.900519 -0.752922 -1.040783 -0.256858  0.395440  0.864073  
172 -0.569940 -0.523001 -0.666608 -0.857929  0.441052  0.284298  

[354 rows x 13 columns]

In [28]:
X_test

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
329 -0.417596 -0.488242 -1.155173 -0.277097 -0.818007  0.068904 -1.859451   
371  0.631340 -0.488242  1.017641 -0.277097  0.659147 -0.097781  1.129047   
219 -0.412215 -0.488242  0.089150  3.700525 -0.040557  0.125891  0.854740   
403  2.413250 -0.488242  1.017641 -0.277097  1.194724 -1.332960  0.984675   
78  -0.418830 -0.488242  0.247067 -0.277097 -1.016689 -0.074986 -0.542058   
..        ...       ...       ...       ...       ...       ...       ...   
4   -0.417389 -0.488242 -1.310165 -0.277097 -0.835284  1.228577 -0.524011   
428  0.417870 -0.488242  1.017641 -0.277097  1.073787 -0.130548  0.338611   
385  1.498810 -0.488242  1.017641 -0.277097  1.255192 -1.435535  1.060470   
308 -0.368870 -0.488242 -0.181355 -0.277097 -0.092387  0.499151  0.497420   
5   -0.421875 -0.488242 -1.310165 -0.277097 -0.835284  0.207096 -0.361593   

          DIS       RAD       TAX   PTRATIO         B     LSTAT  
329  0.674814 -0.637962  0.129256 -0.719220  0.203235 -0.752526  
371 -1.248292  1.661245  1.530926  0.806576  0.103898 -0.443595  
219 -0.205237 -0.523001 -0.785394 -0.950402  0.406405 -0.306762  
403 -0.994588  1.661245  1.530926  0.806576  0.441052  1.000906  
78   0.579502 -0.523001 -0.060801  0.113032  0.325926 -0.047204  
..        ...       ...       ...       ...       ...       ...  
4    1.077737 -0.752922 -1.106115  0.113032  0.441052 -0.827291  
428 -0.883922  1.661245  1.530926  0.806576 -2.850120  1.247769  
385 -1.126122  1.661245  1.530926  0.806576  0.441052  2.558259  
308 -0.227009 -0.637962 -0.619094 -0.025677  0.441052 -1.147507  
5    1.077737 -0.752922 -1.106115  0.113032  0.410571 -1.052994  

[152 rows x 13 columns]

In [29]:
y_train

141    14.4
272    24.4
135    18.1
298    22.5
122    20.5
       ... 
323    18.5
192    36.4
117    19.2
47     16.6
172    23.1
Name: MEDV, Length: 354, dtype: float64

In [30]:
y_test[329]

22.6

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
model = LinearRegression()

In [33]:
model.fit(X_train,y_train)

LinearRegression()

In [34]:
y_pred = model.predict(X_test)

In [35]:
X_train=np.arange(0,len(X_train),1)

In [36]:
X_test=np.arange(0,len(X_test),1)

In [37]:
count=0

In [38]:
y_test

329    22.6
371    50.0
219    23.0
403     8.3
78     21.2
       ... 
4      36.2
428    11.0
385     7.2
308    22.8
5      28.7
Name: MEDV, Length: 152, dtype: float64

In [39]:
y_pred

array([25.22780778, 23.64223665, 29.3985461 , 11.87519728, 21.43673935,
       19.28124691, 20.64828448, 21.24618194, 19.07423154, 20.36995494,
        5.05924148, 16.87255634, 17.24722683,  5.30130837, 40.30585364,
       32.46052125, 22.47281985, 36.53732237, 31.14789013, 23.24409326,
       24.81089919, 24.3370304 , 20.6911936 , 30.44827622, 22.36384839,
        9.93100004, 17.45433275, 18.30853822, 35.67834597, 20.8366093 ,
       18.23604621, 17.80892554, 19.32019859, 23.57876004, 29.11947477,
       19.77334019, 11.10447763, 24.97936588, 18.17007941, 15.59532246,
       26.25399657, 20.88729772, 23.71155767, 15.3978156 , 22.88194483,
       24.83355459, 19.69589379, 23.36002183,  9.94368335, 24.4302679 ,
       21.64828432, 17.87550393, 24.36117546, 30.27546054, 13.55256953,
       21.65262399, 20.64307269, 15.22088608, 13.90503165, 22.25287363,
       17.32874695, 21.61242806, 32.67633792, 31.48212858, 17.80692906,
       32.82949798, 18.92466378, 19.21928818, 18.62607694, 23.48