In [1]:
import cv2

In [2]:
import os

In [3]:
working_directory = os.getcwd()

In [4]:
print(working_directory)

/Users/vanshgadhia/Desktop/Machine Learning


In [5]:
path = working_directory + '/data/training-images/0/0.1.png'

In [6]:
path

'/Users/vanshgadhia/Desktop/Machine Learning/data/training-images/0/0.1.png'

In [7]:
img = cv2.imread(path, cv2.IMREAD_COLOR)

In [8]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [9]:
img.T

array([[[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]],

       [[255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        ...,
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255],
        [255, 255, 255, ..., 255, 255, 255]]], dtype=uint8)

In [10]:
img.shape

(28, 28, 3)

In [11]:
import matplotlib.pyplot as plt

In [12]:
import numpy as np

In [13]:
new_img = img.reshape((img.shape[0]*img.shape[1]), img.shape[2])
new_img = new_img.transpose()

In [14]:
new_img

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [15]:
old_shape = new_img.shape

In [16]:
a_1d_array = np.reshape(new_img, old_shape[0] * old_shape[1])

In [17]:
a_1d_array

array([255, 255, 255, ..., 255, 255, 255], dtype=uint8)

In [18]:
arr_data=[]

In [19]:
y_va = []

In [20]:
for fil in range(0,4):
    dirt = os.listdir(working_directory + '/data/training-images/'+str(fil))
    for pil in dirt:
        if(pil[-3:]=='png'):
            print(pil)
            path = working_directory + '/data/training-images/' + str(fil) + '/' + pil
            y_va.append(fil)
            img = cv2.imread(path, cv2.IMREAD_COLOR)
            new_img = img.reshape((img.shape[0]*img.shape[1]), img.shape[2])
            new_img = new_img.transpose()
            old_shape = new_img.shape
            arr = np.reshape(new_img, old_shape[0] * old_shape[1])
            arr_data.append(arr)

1.4.png
0.29.png
0.15.png
3.6.png
5.0.png
7.2.png
7.3.png
5.1.png
0.1 (2).png
3.7.png
0.14.png
0.28.png
1.5.png
1.7.png
3.5.png
0.16.png
5.3.png
7.1.png
7.0.png
5.2.png
0.17.png
3.4.png
1.6.png
0.8 (2).png
1.2.png
3.0.png
0.13.png
5.6.png
7.4.png
7.5.png
5.7.png
0.9 (2).png
0.12.png
3.1.png
1.3.png
1.1.png
0.10.png
3.3.png
0.38.png
5.5.png
7.7.png
9.8.png
9.9.png
7.6.png
5.4.png
0.39.png
3.2.png
0.11.png
1.0.png
6.1.png
4.3.png
2.5.png
0.7.png
0.6.png
2.4.png
4.2.png
6.0.png
6.2.png
0.49.png
4.0.png
2.6.png
0.4.png
0.5.png
2.7.png
0.2 (2).png
4.1.png
0.48.png
6.3.png
6.7.png
8.8.png
4.5.png
2.3.png
0.1.png
2.2.png
4.4.png
0.3 (2).png
8.9.png
6.6.png
6.4.png
4.6.png
2.0.png
0.2.png
0.3.png
2.1.png
4.7.png
6.5.png
6.8.png
8.7.png
0.43.png
10.0.png
0.42.png
8.6.png
6.9.png
8.4.png
4.9.png
0.40.png
0.6 (2).png
0.41.png
4.8.png
8.5.png
8.1.png
0.45.png
0.7 (2).png
0.8.png
0.9.png
0.50.png
0.44.png
8.0.png
8.2.png
0.46.png
2.9.png
2.8.png
0.47.png
8.3.png
0.5 (2).png
0.34.png
0.20.png
5.9.pn

In [21]:
arr_data

[array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 2

In [22]:
arr_data

[array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 255, 255, ..., 255, 255, 255], dtype=uint8),
 array([255, 2

In [23]:
import pandas as pd

In [24]:
df = pd.DataFrame()

In [25]:
df

Empty DataFrame
Columns: []
Index: []

In [26]:
for pos in range(len(arr_data)):
    df[pos]=arr_data[pos]

/var/folders/dn/bs507yz577q45m4_yg_b4xhw0000gn/T/ipykernel_63550/3607939898.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df[pos]=arr_data[pos]


In [27]:
df = df.T

In [28]:
df

0     1     2     3     4     5     6     7     8     9     ...  2342  \
0     255   255   255   255   255   255   255   255   255   255  ...   255   
1     255   255   255   255   255   255   255   255   255   255  ...   255   
2     255   255   255   255   255   255   255   255   255   255  ...   255   
3     255   255   255   255   255   255   255   255   255   255  ...   255   
4     255   255   255   255   255   255   255   255   255   255  ...   255   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
445   255   255   255   255   255   255   255   255   255   255  ...   255   
446   255   255   255   255   255   255   255   255   255   255  ...   255   
447   255   255   255   255   255   255   255   255   255   255  ...   255   
448   255   255   255   255   255   255   255   255   255   255  ...   255   
449   255   255   255   255   255   255   255   255   255   255  ...   255   

     2343  2344  2345  2346  2347  2348  2349  2350  2351  
0     255   255   255   255   255   255   255   255   255  
1     255   255   255   255   255   255   255   255   255  
2     255   255   255   255   255   255   255   255   255  
3     255   255   255   255   255   255   255   255   255  
4     255   255   255   255   255   255   255   255   255  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
445   255   255   255   255   255   255   255   255   255  
446   255   255   255   255   255   255   255   255   255  
447   255   255   255   255   255   255   255   255   255  
448   255   255   255   255   255   255   255   255   255  
449   255   255   255   255   255   255   255   255   255  

[450 rows x 2352 columns]

In [29]:
df['Y Value'] = y_va

In [30]:
df

0    1    2    3    4    5    6    7    8    9  ...  2343  2344  2345  \
0    255  255  255  255  255  255  255  255  255  255  ...   255   255   255   
1    255  255  255  255  255  255  255  255  255  255  ...   255   255   255   
2    255  255  255  255  255  255  255  255  255  255  ...   255   255   255   
3    255  255  255  255  255  255  255  255  255  255  ...   255   255   255   
4    255  255  255  255  255  255  255  255  255  255  ...   255   255   255   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...   ...   
445  255  255  255  255  255  255  255  255  255  255  ...   255   255   255   
446  255  255  255  255  255  255  255  255  255  255  ...   255   255   255   
447  255  255  255  255  255  255  255  255  255  255  ...   255   255   255   
448  255  255  255  255  255  255  255  255  255  255  ...   255   255   255   
449  255  255  255  255  255  255  255  255  255  255  ...   255   255   255   

     2346  2347  2348  2349  2350  2351  Y Value  
0     255   255   255   255   255   255        0  
1     255   255   255   255   255   255        0  
2     255   255   255   255   255   255        0  
3     255   255   255   255   255   255        0  
4     255   255   255   255   255   255        0  
..    ...   ...   ...   ...   ...   ...      ...  
445   255   255   255   255   255   255        3  
446   255   255   255   255   255   255        3  
447   255   255   255   255   255   255        3  
448   255   255   255   255   255   255        3  
449   255   255   255   255   255   255        3  

[450 rows x 2353 columns]

In [31]:
from sklearn.tree import DecisionTreeClassifier

In [32]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
from sklearn.pipeline import Pipeline

In [34]:
from sklearn.model_selection import GridSearchCV

In [35]:
from sklearn.neighbors import KNeighborsClassifier

In [36]:
pipeline=Pipeline([('classifier',KNeighborsClassifier(metric='euclidean'))])

In [37]:
search_space = [{'classifier': [KNeighborsClassifier()],
                 'classifier__n_neighbors': np.arange(1, 25),
                 'classifier__metric': ['euclidean','manhattan','minkowski']}]

In [38]:
clf = GridSearchCV(pipeline, search_space, cv=5)

In [39]:
df = df.drop(columns = ['Y Value'], axis =1)

In [40]:
df

0     1     2     3     4     5     6     7     8     9     ...  2342  \
0     255   255   255   255   255   255   255   255   255   255  ...   255   
1     255   255   255   255   255   255   255   255   255   255  ...   255   
2     255   255   255   255   255   255   255   255   255   255  ...   255   
3     255   255   255   255   255   255   255   255   255   255  ...   255   
4     255   255   255   255   255   255   255   255   255   255  ...   255   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
445   255   255   255   255   255   255   255   255   255   255  ...   255   
446   255   255   255   255   255   255   255   255   255   255  ...   255   
447   255   255   255   255   255   255   255   255   255   255  ...   255   
448   255   255   255   255   255   255   255   255   255   255  ...   255   
449   255   255   255   255   255   255   255   255   255   255  ...   255   

     2343  2344  2345  2346  2347  2348  2349  2350  2351  
0     255   255   255   255   255   255   255   255   255  
1     255   255   255   255   255   255   255   255   255  
2     255   255   255   255   255   255   255   255   255  
3     255   255   255   255   255   255   255   255   255  
4     255   255   255   255   255   255   255   255   255  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
445   255   255   255   255   255   255   255   255   255  
446   255   255   255   255   255   255   255   255   255  
447   255   255   255   255   255   255   255   255   255  
448   255   255   255   255   255   255   255   255   255  
449   255   255   255   255   255   255   255   255   255  

[450 rows x 2352 columns]

In [41]:
clf.fit(df,y_va)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('classifier',
                                        KNeighborsClassifier(metric='euclidean'))]),
             param_grid=[{'classifier': [KNeighborsClassifier(metric='euclidean',
                                                              n_neighbors=2)],
                          'classifier__metric': ['euclidean', 'manhattan',
                                                 'minkowski'],
                          'classifier__n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])}])

In [42]:
df_grid = pd.DataFrame(data=clf.cv_results_)

In [43]:
df_grid

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.009737      0.000486         0.020057        0.002341   
1        0.009501      0.000267         0.018406        0.001843   
2        0.009229      0.000130         0.016572        0.000785   
3        0.009370      0.000124         0.017043        0.000563   
4        0.009350      0.000153         0.017143        0.000479   
..            ...           ...              ...             ...   
67       0.009376      0.000013         0.018325        0.001254   
68       0.009514      0.000220         0.018979        0.001422   
69       0.009273      0.000121         0.017068        0.001092   
70       0.009319      0.000120         0.017619        0.001131   
71       0.009257      0.000078         0.016818        0.000484   

                                     param_classifier  \
0   KNeighborsClassifier(metric='euclidean', n_nei...   
1   KNeighborsClassifier(metric='euclidean', n_nei...   
2   KNeighborsClassifier(metric='euclidean', n_nei...   
3   KNeighborsClassifier(metric='euclidean', n_nei...   
4   KNeighborsClassifier(metric='euclidean', n_nei...   
..                                                ...   
67  KNeighborsClassifier(metric='euclidean', n_nei...   
68  KNeighborsClassifier(metric='euclidean', n_nei...   
69  KNeighborsClassifier(metric='euclidean', n_nei...   
70  KNeighborsClassifier(metric='euclidean', n_nei...   
71  KNeighborsClassifier(metric='euclidean', n_nei...   

   param_classifier__metric param_classifier__n_neighbors  \
0                 euclidean                             1   
1                 euclidean                             2   
2                 euclidean                             3   
3                 euclidean                             4   
4                 euclidean                             5   
..                      ...                           ...   
67                minkowski                            20   
68                minkowski                            21   
69                minkowski                            22   
70                minkowski                            23   
71                minkowski                            24   

                                               params  split0_test_score  \
0   {'classifier': KNeighborsClassifier(metric='eu...           0.700000   
1   {'classifier': KNeighborsClassifier(metric='eu...           0.855556   
2   {'classifier': KNeighborsClassifier(metric='eu...           0.755556   
3   {'classifier': KNeighborsClassifier(metric='eu...           0.822222   
4   {'classifier': KNeighborsClassifier(metric='eu...           0.788889   
..                                                ...                ...   
67  {'classifier': KNeighborsClassifier(metric='eu...           0.611111   
68  {'classifier': KNeighborsClassifier(metric='eu...           0.566667   
69  {'classifier': KNeighborsClassifier(metric='eu...           0.566667   
70  {'classifier': KNeighborsClassifier(metric='eu...           0.577778   
71  {'classifier': KNeighborsClassifier(metric='eu...           0.566667   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.766667           0.677778           0.733333   
1            0.744444           0.866667           0.822222   
2            0.755556           0.788889           0.788889   
3            0.744444           0.800000           0.800000   
4            0.755556           0.788889           0.788889   
..                ...                ...                ...   
67           0.544444           0.555556           0.577778   
68           0.544444           0.533333           0.566667   
69           0.500000           0.522222           0.555556   
70           0.488889           0.522222           0.544444   
71           0.500000           0.511111           0.522222   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0            0.777778    

In [44]:
search_space = [{'classifier': [DecisionTreeClassifier()],
                 'classifier__criterion': ['entropy', 'gini'],
                 'classifier__min_samples_split': [2,3,4]},
                {'classifier': [RandomForestClassifier()],
                 'classifier__criterion': ['entropy', 'gini'],
                 'classifier__min_samples_split': [2,3,4],
                 'classifier__n_estimators': [10,100]}]

In [45]:
clf = GridSearchCV(pipeline, search_space)

In [46]:
clf.fit(df,y_va)

GridSearchCV(estimator=Pipeline(steps=[('classifier',
                                        KNeighborsClassifier(metric='euclidean'))]),
             param_grid=[{'classifier': [DecisionTreeClassifier()],
                          'classifier__criterion': ['entropy', 'gini'],
                          'classifier__min_samples_split': [2, 3, 4]},
                         {'classifier': [RandomForestClassifier(min_samples_split=4)],
                          'classifier__criterion': ['entropy', 'gini'],
                          'classifier__min_samples_split': [2, 3, 4],
                          'classifier__n_estimators': [10, 100]}])

In [47]:
df_grid = pd.DataFrame(data=clf.cv_results_)

In [48]:
df_grid

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.039280      0.001297         0.008979        0.000105   
1        0.037814      0.001530         0.008875        0.000207   
2        0.039875      0.002359         0.009291        0.000737   
3        0.037987      0.001772         0.008674        0.000055   
4        0.038049      0.001746         0.008778        0.000064   
5        0.037220      0.002060         0.008623        0.000061   
6        0.023292      0.001053         0.009791        0.000477   
7        0.137163      0.002229         0.013947        0.000248   
8        0.022271      0.000256         0.009262        0.000093   
9        0.134832      0.000649         0.013693        0.000234   
10       0.021981      0.000221         0.009373        0.000177   
11       0.132064      0.002083         0.013663        0.000214   
12       0.021550      0.000207         0.009368        0.000210   
13       0.142392      0.016718         0.014241        0.000695   
14       0.024409      0.003098         0.010143        0.000632   
15       0.139805      0.012830         0.014352        0.000543   
16       0.024708      0.002391         0.010462        0.000907   
17       0.134624      0.003681         0.014202        0.000400   

                               param_classifier param_classifier__criterion  \
0                      DecisionTreeClassifier()                     entropy   
1                      DecisionTreeClassifier()                     entropy   
2                      DecisionTreeClassifier()                     entropy   
3                      DecisionTreeClassifier()                        gini   
4                      DecisionTreeClassifier()                        gini   
5                      DecisionTreeClassifier()                        gini   
6   RandomForestClassifier(min_samples_split=4)                     entropy   
7   RandomForestClassifier(min_samples_split=4)                     entropy   
8   RandomForestClassifier(min_samples_split=4)                     entropy   
9   RandomForestClassifier(min_samples_split=4)                     entropy   
10  RandomForestClassifier(min_samples_split=4)                     entropy   
11  RandomForestClassifier(min_samples_split=4)                     entropy   
12  RandomForestClassifier(min_samples_split=4)                        gini   
13  RandomForestClassifier(min_samples_split=4)                        gini   
14  RandomForestClassifier(min_samples_split=4)                        gini   
15  RandomForestClassifier(min_samples_split=4)                        gini   
16  RandomForestClassifier(min_samples_split=4)                        gini   
17  RandomForestClassifier(min_samples_split=4)                        gini   

   param_classifier__min_samples_split param_classifier__n_estimators  \
0                                    2                            NaN   
1                                    3                            NaN   
2                                    4                            NaN   
3                                    2                            NaN   
4                                    3                            NaN   
5                                    4                            NaN   
6                                    2                             10   
7                                    2                            100   
8                                    3                             10   
9                                    3                            100   
10                                   4                             10   
11                                   4                            100   
12                                   2                             10   
13                                   2                            100   
14                                   3                             10   
15                                   3   

In [49]:
from sklearn.decomposition import PCA

In [50]:
pca = PCA(n_components=10)

In [51]:
pca.fit(df)

PCA(n_components=10)

In [52]:
df.shape

(450, 2352)

In [53]:
x_pca = pca.transform(df)

In [54]:
x_pca

array([[1074.02239239,  -98.55236926,  296.72871045, ..., -435.86897716,
        -908.90658437,   81.33815237],
       [ 424.10839875, -448.81315229, 1407.75681763, ...,  964.25917272,
         494.63233193,   87.81348362],
       [ -56.93113148, -771.67817389,  946.04768706, ...,  -32.3030458 ,
          60.44534888, -515.53273904],
       ...,
       [-404.0372616 , -926.86898328,    4.83452008, ..., -375.44689608,
         -23.9498105 ,  795.43406756],
       [-372.68339807,  111.57050767,  -79.16896341, ...,  203.70290508,
        -227.01953754, -347.00900198],
       [ 254.05725331,  -29.95534086, -144.63393496, ...,  -10.36321146,
          24.02774623, -580.71109252]])

In [55]:
df_pca = pd.DataFrame(data=x_pca)

In [56]:
df_pca

0           1            2            3           4  \
0    1074.022392  -98.552369   296.728710    21.231572 -572.950267   
1     424.108399 -448.813152  1407.756818  -119.387110 -234.603221   
2     -56.931131 -771.678174   946.047687   345.464801  115.359532   
3     457.522843 -725.859720   -47.064486  -968.130780 -653.622625   
4    1351.648476  706.543873   161.570633    95.302017  126.107877   
..           ...         ...          ...          ...         ...   
445  -501.980936 -747.905610   -30.491743  -669.987728  504.598012   
446  -137.843270 -605.212074  -773.076007     8.044488 -405.719650   
447  -404.037262 -926.868983     4.834520   -35.406711  548.163473   
448  -372.683398  111.570508   -79.168963  -802.199695  156.028663   
449   254.057253  -29.955341  -144.633935  1097.803140  -28.144395   

               5           6           7           8           9  
0     303.878967  339.286279 -435.868977 -908.906584   81.338152  
1     243.939568  313.855364  964.259173  494.632332   87.813484  
2   -1262.959224   57.148533  -32.303046   60.445349 -515.532739  
3    -644.107691  267.401042  295.916359  566.504322 -655.632225  
4    -232.223612  -96.892594 -606.750722   -0.423777 -811.183964  
..           ...         ...         ...         ...         ...  
445   555.408440  448.617207  175.434153 -604.312654  144.098784  
446   196.613206  -47.801206  716.822590  159.951216 -500.712590  
447   159.553306 -146.903831 -375.446896  -23.949810  795.434068  
448  -425.592091   33.419895  203.702905 -227.019538 -347.009002  
449  -174.254223 -908.380184  -10.363211   24.027746 -580.711093  

[450 rows x 10 columns]

In [57]:
best_model = RandomForestClassifier(criterion='gini',n_estimators=100,min_samples_split=4)

In [58]:
best_model.fit(df_pca,y_va)

RandomForestClassifier(min_samples_split=4)

In [59]:
y_test_vals = []

In [60]:
arr_test_data=[]

In [61]:
for fil in range(0,4):
    dirt = os.listdir(working_directory + '/data/test-images/'+str(fil))
    for pil in dirt:
        if(pil[-3:]=='png'):
            print(pil)
            path = working_directory + '/data/test-images/' + str(fil) + '/' + pil
            y_test_vals.append(fil)
            img = cv2.imread(path, cv2.IMREAD_COLOR)
            new_img = img.reshape((img.shape[0]*img.shape[1]), img.shape[2])
            new_img = new_img.transpose()
            old_shape = new_img.shape
            arr = np.reshape(new_img, old_shape[0] * old_shape[1])
            arr_test_data.append(arr)

13.9.png
13.8.png
11.8.png
11.9.png
10.8.png
10.9.png
12.9.png
12.8.png
14.9.png
14.8.png
14.5.png
10.1.png
12.3.png
12.2.png
14.4.png
14.6.png
10.2.png
12.0.png
12.1.png
10.3.png
14.7.png
14.3.png
10.7.png
12.5.png
12.4.png
10.6.png
14.2.png
14.0.png
10.4.png
12.6.png
12.7.png
10.5.png
14.1.png
13.0.png
11.2.png
11.3.png
13.1.png
13.3.png
11.1.png
11.0.png
13.2.png
13.6.png
11.4.png
15.0.png
11.5.png
13.7.png
13.5.png
11.7.png
11.6.png
13.4.png
13.9.png
13.8.png
11.8.png
11.9.png
10.8.png
10.9.png
12.9.png
12.8.png
14.9.png
14.8.png
14.5.png
10.1.png
12.3.png
12.2.png
14.4.png
14.6.png
10.2.png
12.0.png
12.1.png
10.3.png
14.7.png
14.3.png
10.7.png
12.5.png
12.4.png
10.6.png
14.2.png
14.0.png
10.4.png
12.6.png
12.7.png
10.5.png
14.1.png
13.0.png
11.2.png
11.3.png
13.1.png
13.3.png
11.1.png
11.0.png
13.2.png
13.6.png
11.4.png
15.0.png
11.5.png
13.7.png
13.5.png
11.7.png
11.6.png
13.4.png
5.0.png
7.2.png
7.3.png
5.1.png
5.3.png
7.1.png
7.0.png
5.2.png
5.6.png
7.4.png
7.5.png
5.7.png
5.5.

In [62]:
df_test = pd.DataFrame()

In [63]:
for pos in range(len(arr_test_data)):
    df_test[pos]=arr_test_data[pos]

/var/folders/dn/bs507yz577q45m4_yg_b4xhw0000gn/T/ipykernel_63550/3998666209.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df_test[pos]=arr_test_data[pos]


In [64]:
df_test = df_test.T

In [65]:
df_test

0     1     2     3     4     5     6     7     8     9     ...  2342  \
0     255   255   255   255   255   255   255   255   255   255  ...   255   
1     255   255   255   255   255   255   255   255   255   255  ...   255   
2     255   255   255   255   255   255   255   255   255   255  ...   255   
3     255   255   255   255   255   255   255   255   255   255  ...   255   
4     255   255   255   255   255   255   255   255   255   255  ...   255   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
199   255   255   255   255   255   255   255   255   255   255  ...   255   
200   255   255   255   255   255   255   255   255   255   255  ...   255   
201   255   255   255   255   255   255   255   255   255   255  ...   255   
202   255   255   255   255   255   255   255   255   255   255  ...   255   
203   255   255   255   255   255   255   255   255   255   255  ...   255   

     2343  2344  2345  2346  2347  2348  2349  2350  2351  
0     255   255   255   255   255   255   255   255   255  
1     255   255   255   255   255   255   255   255   255  
2     255   255   255   255   255   255   255   255   255  
3     255   255   255   255   255   255   255   255   255  
4     255   255   255   255   255   255   255   255   255  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
199   255   255   255   255   255   255   255   255   255  
200   255   255   255   255   255   255   255   255   255  
201   255   255   255   255   255   255   255   255   255  
202   255   255   255   255   255   255   255   255   255  
203   255   255   255   255   255   255   255   255   255  

[204 rows x 2352 columns]

In [66]:
pca_test = PCA(n_components=10)

In [67]:
pca_test.fit(df_test)

PCA(n_components=10)

In [68]:
test_pca = pca.transform(df_test)

In [69]:
df_test_pca = pd.DataFrame(data=test_pca)

In [70]:
df_test_pca

0           1           2           3           4           5  \
0    1468.710765  -58.054324  684.037272  718.197047  205.059384  370.084924   
1    1533.432163  508.797228  -16.532773  944.516961  107.590290 -212.083152   
2    1453.962894  -42.451400 -567.856245  133.082327  165.579564  -75.197160   
3     976.230648    5.705227  525.237331  325.677329  852.042881   61.981375   
4    1526.088562  252.393128 -560.972936  657.616311  -16.401087 -115.553620   
..           ...         ...         ...         ...         ...         ...   
199   -58.423659 -402.922123 -477.047849  397.309601    2.171848  913.124839   
200  -706.898401  120.021391 -175.568535  -21.778893  356.608966   30.464627   
201   -43.916003 -689.218618 -383.126883 -131.476096   49.191582  746.168335   
202  -171.605788  661.378208    8.544991   64.399405  430.401617  105.395199   
203  -810.881715 -185.996404  221.086397 -149.654777  265.375115 -667.044717   

              6           7           8           9  
0    265.473617 -363.933684   42.110501 -195.702886  
1   -220.052377 -194.189069 -239.800242 -366.696077  
2    203.081642  116.868732  723.786723  522.282016  
3   -459.197271 -140.288411  903.379539 -540.292300  
4   -142.247610 -617.552826 -225.192272  362.709463  
..          ...         ...         ...         ...  
199 -381.240743  201.520980  155.701307 -343.681428  
200  114.256698 -200.857285 -191.976704   72.292457  
201 -131.822531  605.081575 -167.328060   69.816165  
202 -304.400746  180.700137  233.131687 -265.122545  
203 -385.846885 -210.387132 -152.274989 -304.299328  

[204 rows x 10 columns]

In [71]:
preds = best_model.predict(df_test_pca)

In [72]:
preds

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 3, 0, 0, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 0, 1, 1, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 0, 1, 2, 1, 2, 1, 0, 0, 2, 2, 2, 1, 2, 1, 0, 2, 2, 0,
       2, 2, 2, 2, 2, 1, 0, 1, 2, 2, 2, 2, 2, 1, 3, 2, 2, 2, 0, 2, 1, 2,
       0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       2, 3, 0, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 0, 3, 3, 3, 3, 3, 3, 0,
       3, 3, 3, 3, 1, 3])

In [73]:
count=0

In [74]:
for pos in range(0,len(y_test_vals)):
    if(y_test_vals[pos]==preds[pos]):
        count+=1

In [75]:
accuracy = (count/len(preds)*100)

In [76]:
print('The accuracy of the model is: ' + str(accuracy) + '%')

The accuracy of the model is: 83.82352941176471%


In [77]:
model = RandomForestClassifier()

In [78]:
pipeline=Pipeline(steps=[('pca',PCA()), ('model',model)])

In [79]:
search_space = {"pca":[None,PCA(10),PCA(30),PCA(50),PCA(100)],
                "model__min_samples_split":[2,4,5],
                "model__criterion":['gini','entropy'],
                "model__n_estimators":[10,100]}

In [80]:
clf = GridSearchCV(pipeline, search_space)

In [81]:
clf.fit(df, y_va)

GridSearchCV(estimator=Pipeline(steps=[('pca', PCA()),
                                       ('model', RandomForestClassifier())]),
             param_grid={'model__criterion': ['gini', 'entropy'],
                         'model__min_samples_split': [2, 4, 5],
                         'model__n_estimators': [10, 100],
                         'pca': [None, PCA(n_components=10),
                                 PCA(n_components=30), PCA(n_components=50),
                                 PCA(n_components=100)]})

In [82]:
df_grid = pd.DataFrame(data=clf.cv_results_)

In [83]:
df_grid

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.024906      0.002181         0.010159        0.000311   
1        0.068954      0.002031         0.013017        0.002949   
2        0.114375      0.005917         0.011486        0.000337   
3        0.169908      0.037680         0.014384        0.002086   
4        0.272688      0.027217         0.016282        0.004133   
5        0.161285      0.012939         0.015217        0.000565   
6        0.178206      0.015059         0.016650        0.000964   
7        0.248060      0.026107         0.016960        0.001296   
8        0.276002      0.013743         0.016526        0.000464   
9        0.423522      0.007937         0.017215        0.000826   
10       0.022210      0.000175         0.009660        0.000035   
11       0.071120      0.005869         0.010981        0.000432   
12       0.117952      0.006431         0.012653        0.001470   
13       0.134812      0.011753         0.011911        0.000509   
14       0.227227      0.009249         0.012536        0.000421   
15       0.128432      0.002271         0.013697        0.000215   
16       0.158437      0.004564         0.015027        0.000133   
17       0.220276      0.006437         0.015711        0.000255   
18       0.268548      0.007740         0.017495        0.000906   
19       0.403721      0.006168         0.018091        0.001398   
20       0.022971      0.001374         0.009735        0.000241   
21       0.072976      0.004443         0.010992        0.000455   
22       0.111448      0.004288         0.011750        0.000491   
23       0.135900      0.010958         0.012243        0.000542   
24       0.239282      0.024290         0.012898        0.000468   
25       0.161984      0.028855         0.015030        0.000482   
26       0.157991      0.004415         0.015712        0.000486   
27       0.219850      0.005071         0.016073        0.000340   
28       0.255454      0.003583         0.017211        0.000217   
29       0.378354      0.012124         0.017815        0.000971   
30       0.023163      0.000216         0.009853        0.000159   
31       0.085979      0.009648         0.012310        0.000808   
32       0.122482      0.012461         0.012639        0.000609   
33       0.141058      0.011829         0.012184        0.000655   
34       0.243726      0.012992         0.014172        0.002023   
35       0.136714      0.004174         0.013805        0.000108   
36       0.179481      0.003501         0.015747        0.000318   
37       0.246777      0.004899         0.015998        0.000418   
38       0.297929      0.002070         0.016438        0.000968   
39       0.456540      0.008958         0.018126        0.002076   
40       0.022736      0.000058         0.009635        0.000042   
41       0.070769      0.003902         0.011057        0.000880   
42       0.119338      0.005294         0.011680        0.000406   
43       0.150921      0.021774         0.012647        0.001229   
44       0.243574      0.015194         0.013441        0.000670   
45       0.133193      0.003020         0.013592        0.000283   
46       0.172087      0.001700         0.015539        0.000519   
47       0.253693      0.005782         0.016377        0.000383   
48       0.306300      0.005939         0.017008        0.001302   
49       0.461881      0.014597         0.017853        0.000875   
50       0.021774      0.000205         0.009327        0.000048   
51       0.069253      0.001332         0.010864        0.000317   
52       0.114240      0.006542         0.011531        0.000633   
53       0.131443      0.003553         0.011863        0.000550   
54       0.224097      0.016038         0.013754        0.001524   
55       0.131667      0.002814         0.013594        0.000310   
56       0.171996      0.002255         0.015557        0.000594   
57       0.247785      0.003794         0.015995        0.00

In [84]:
test_model = RandomForestClassifier(criterion='gini',n_estimators=100,min_samples_split=4)

In [85]:
df_grid.sort_values('rank_test_score')

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
5        0.161285      0.012939         0.015217        0.000565   
15       0.128432      0.002271         0.013697        0.000215   
25       0.161984      0.028855         0.015030        0.000482   
18       0.268548      0.007740         0.017495        0.000906   
55       0.131667      0.002814         0.013594        0.000310   
47       0.253693      0.005782         0.016377        0.000383   
35       0.136714      0.004174         0.013805        0.000108   
57       0.247785      0.003794         0.015995        0.000590   
48       0.306300      0.005939         0.017008        0.001302   
17       0.220276      0.006437         0.015711        0.000255   
45       0.133193      0.003020         0.013592        0.000283   
8        0.276002      0.013743         0.016526        0.000464   
38       0.297929      0.002070         0.016438        0.000968   
56       0.171996      0.002255         0.015557        0.000594   
7        0.248060      0.026107         0.016960        0.001296   
9        0.423522      0.007937         0.017215        0.000826   
37       0.246777      0.004899         0.015998        0.000418   
58       0.302335      0.009904         0.017401        0.001532   
16       0.158437      0.004564         0.015027        0.000133   
49       0.461881      0.014597         0.017853        0.000875   
6        0.178206      0.015059         0.016650        0.000964   
19       0.403721      0.006168         0.018091        0.001398   
46       0.172087      0.001700         0.015539        0.000519   
28       0.255454      0.003583         0.017211        0.000217   
36       0.179481      0.003501         0.015747        0.000318   
26       0.157991      0.004415         0.015712        0.000486   
27       0.219850      0.005071         0.016073        0.000340   
20       0.022971      0.001374         0.009735        0.000241   
39       0.456540      0.008958         0.018126        0.002076   
59       0.439061      0.005722         0.017260        0.000266   
10       0.022210      0.000175         0.009660        0.000035   
29       0.378354      0.012124         0.017815        0.000971   
30       0.023163      0.000216         0.009853        0.000159   
12       0.117952      0.006431         0.012653        0.001470   
0        0.024906      0.002181         0.010159        0.000311   
42       0.119338      0.005294         0.011680        0.000406   
41       0.070769      0.003902         0.011057        0.000880   
31       0.085979      0.009648         0.012310        0.000808   
2        0.114375      0.005917         0.011486        0.000337   
50       0.021774      0.000205         0.009327        0.000048   
52       0.114240      0.006542         0.011531        0.000633   
22       0.111448      0.004288         0.011750        0.000491   
21       0.072976      0.004443         0.010992        0.000455   
11       0.071120      0.005869         0.010981        0.000432   
40       0.022736      0.000058         0.009635        0.000042   
51       0.069253      0.001332         0.010864        0.000317   
32       0.122482      0.012461         0.012639        0.000609   
23       0.135900      0.010958         0.012243        0.000542   
1        0.068954      0.002031         0.013017        0.002949   
43       0.150921      0.021774         0.012647        0.001229   
13       0.134812      0.011753         0.011911        0.000509   
24       0.239282      0.024290         0.012898        0.000468   
3        0.169908      0.037680         0.014384        0.002086   
53       0.131443      0.003553         0.011863        0.000550   
33       0.141058      0.011829         0.012184        0.000655   
44       0.243574      0.015194         0.013441        0.000670   
54       0.224097      0.016038         0.013754        0.001524   
14       0.227227      0.009249         0.012536        0.00